name: Windows

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - ".github/workflows/windows.yml"
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      PROJECT_RELEASE_PATH: ${{ github.event.repository.name }}_dev_win_x64
      PROJECT_RESOURCES_PATH: assets

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout raylib
        uses: actions/checkout@v4
        with:
          repository: raysan5/raylib
          path: raylib

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DRAYLIB_SRC_PATH=../raylib/src ..
          cmake --build . --config Release
        shell: bash

      - name: Prepare release folder
        run: |
          mkdir ${{ env.PROJECT_RELEASE_PATH }}
          cp build/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.exe ${{ env.PROJECT_RELEASE_PATH }}
          cp -r src/${{ env.PROJECT_RESOURCES_PATH }} ${{ env.PROJECT_RELEASE_PATH }}
          cp README.md LICENSE ${{ env.PROJECT_RELEASE_PATH }}
        shell: bash

      - name: Package artifact
        run: 7z a "${{ env.PROJECT_RELEASE_PATH }}.zip" "${{ env.PROJECT_RELEASE_PATH }}"
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_RELEASE_PATH }}.zip
          path: ./${{ env.PROJECT_RELEASE_PATH }}.zip

      - name: Upload to Release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.PROJECT_RELEASE_PATH }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
